# Generated by Django 5.2.16 on 2026-07-22 06:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('terrain_publie', 'Terrain publié'), ('terrain_modifie', 'Terrain modifié'), ('terrain_archive', 'Terrain archivé'), ('maison_publiee', 'Maison publiée'), ('maison_modifiee', 'Maison modifiée'), ('maison_archivee', 'Maison archivée')], db_index=True, max_length=40)),
                ('cible_type', models.CharField(db_index=True, max_length=20)),
                ('cible_id', models.UUIDField(db_index=True)),
                ('message', models.CharField(max_length=255)),
                ('acteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['-created_at'],
            },
        ),
    ]
