# Generated by Django 5.2.16 on 2026-07-19 14:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('villa', 'Villa'), ('appartement', 'Appartement'), ('duplex', 'Duplex'), ('studio', 'Studio'), ('bureau', 'Bureau')], db_index=True, max_length=20)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('loue', 'Loué'), ('vendu', 'Vendu'), ('en_travaux', 'En travaux'), ('archive', 'Archivé')], db_index=True, default='disponible', max_length=20)),
                ('prix', models.DecimalField(decimal_places=0, max_digits=15)),
                ('ville', models.CharField(db_index=True, max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('surface_m2', models.FloatField()),
                ('surface_terrain_m2', models.FloatField(blank=True, null=True)),
                ('chambres', models.PositiveIntegerField(default=0)),
                ('salles_de_bain', models.PositiveIntegerField(default=0)),
                ('etages', models.PositiveIntegerField(default=1)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('titre_foncier', models.CharField(blank=True, max_length=100)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('videos', models.JSONField(blank=True, default=list)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('date_ajout', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maisons_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maison',
                'verbose_name_plural': 'Maisons',
                'ordering': ['-date_ajout'],
                'indexes': [models.Index(fields=['type', 'statut'], name='maisons_mai_type_b82416_idx'), models.Index(fields=['ville', 'statut'], name='maisons_mai_ville_ea6591_idx')],
            },
        ),
    ]
