# Generated by Django 5.2.16 on 2026-07-19 14:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('bornes', models.JSONField(help_text='Liste de {latitude, longitude} — minimum 3 points.')),
                ('surface_m2', models.FloatField(editable=False, help_text='Surface calculée automatiquement depuis les bornes.')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('en_negociation', 'En négociation'), ('vendu', 'Vendu'), ('archive', 'Archivé')], db_index=True, default='disponible', max_length=20)),
                ('prix', models.DecimalField(decimal_places=0, max_digits=15)),
                ('ville', models.CharField(db_index=True, max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('titre_foncier', models.CharField(blank=True, max_length=100)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('videos', models.JSONField(blank=True, default=list)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('date_ajout', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terrains_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Terrain',
                'verbose_name_plural': 'Terrains',
                'ordering': ['-date_ajout'],
                'indexes': [models.Index(fields=['statut', 'ville'], name='terrains_te_statut_c01ca5_idx'), models.Index(fields=['prix'], name='terrains_te_prix_be1b63_idx')],
            },
        ),
    ]
