# Generated by Django 5.2.16 on 2026-07-22 06:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, default=list, help_text='Liste de points clés (chaînes).')),
                ('prix_indicatif', models.CharField(blank=True, max_length=120)),
                ('icon', models.CharField(default='Briefcase', help_text='Nom d’icône Lucide (ex. FileSearch, Home, Ruler).', max_length=60)),
                ('categorie', models.CharField(choices=[('audit', 'Audit & expertise'), ('vente', 'Vente'), ('gestion', 'Gestion & accompagnement')], db_index=True, max_length=20)),
                ('ordre', models.PositiveIntegerField(db_index=True, default=0)),
                ('actif', models.BooleanField(db_index=True, default=True)),
                ('phare', models.BooleanField(default=False, help_text='Affiché en avant sur la page d’accueil.')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['ordre', 'titre'],
            },
        ),
    ]
