# Generated by Django 5.2.16 on 2026-07-19 14:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('client', 'Client')], db_index=True, default='client', max_length=20, verbose_name='Rôle')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu')], db_index=True, default='actif', max_length=20, verbose_name='Statut')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(default='fr', max_length=10)),
                ('devise', models.CharField(default='XAF', max_length=10)),
                ('format_date', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('fuseau', models.CharField(default='Africa/Douala', max_length=50)),
                ('dark_mode', models.BooleanField(default=False)),
                ('accent_color', models.CharField(blank=True, max_length=20)),
                ('notif_transactions', models.BooleanField(default=True)),
                ('notif_messages', models.BooleanField(default=True)),
                ('notif_agenda', models.BooleanField(default=True)),
                ('notif_rapports', models.BooleanField(default=False)),
                ('notif_promotions', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence utilisateur',
                'verbose_name_plural': 'Préférences utilisateurs',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'statut'], name='accounts_us_role_dba9a1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
    ]
