# Generated by Django 5.2.16 on 2026-07-22 03:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(db_index=True, max_length=120, unique=True)),
                ('region', models.CharField(blank=True, db_index=True, max_length=80)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('actif', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'ordering': ['nom'],
            },
        ),
    ]
