# Generated by Django 5.2.16 on 2026-07-19 14:41

import apps.common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('contrat', 'Contrat'), ('titre_foncier', 'Titre foncier'), ('permis', 'Permis'), ('photo', 'Photo'), ('autre', 'Autre')], db_index=True, max_length=30)),
                ('fichier', models.FileField(upload_to=apps.common.validators.upload_to_medias, validators=[apps.common.validators.validate_document_file])),
                ('taille_kb', models.PositiveIntegerField(default=0, editable=False)),
                ('bien_type', models.CharField(choices=[('terrain', 'Terrain'), ('maison', 'Maison'), ('aucun', 'Aucun')], default='aucun', max_length=20)),
                ('bien_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('bien_associe', models.CharField(blank=True, help_text='Libellé libre (compat frontend mock).', max_length=255)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_ajoutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
