/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtilisateursRouteImport } from './routes/utilisateurs'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TerrainsRouteImport } from './routes/terrains'
import { Route as RapportsRouteImport } from './routes/rapports'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as MessagerieRouteImport } from './routes/messagerie'
import { Route as MaisonsRouteImport } from './routes/maisons'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as ClientCarteRouteImport } from './routes/client.carte'
import { Route as ClientTerrainsIndexRouteImport } from './routes/client.terrains.index'
import { Route as ClientMaisonsIndexRouteImport } from './routes/client.maisons.index'
import { Route as ClientTerrainsIdRouteImport } from './routes/client.terrains.$id'
import { Route as ClientMaisonsIdRouteImport } from './routes/client.maisons.$id'

const UtilisateursRoute = UtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TerrainsRoute = TerrainsRouteImport.update({
  id: '/terrains',
  path: '/terrains',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagerieRoute = MessagerieRouteImport.update({
  id: '/messagerie',
  path: '/messagerie',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisonsRoute = MaisonsRouteImport.update({
  id: '/maisons',
  path: '/maisons',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/client/',
  path: '/client/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientCarteRoute = ClientCarteRouteImport.update({
  id: '/client/carte',
  path: '/client/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientTerrainsIndexRoute = ClientTerrainsIndexRouteImport.update({
  id: '/client/terrains/',
  path: '/client/terrains/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientMaisonsIndexRoute = ClientMaisonsIndexRouteImport.update({
  id: '/client/maisons/',
  path: '/client/maisons/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientTerrainsIdRoute = ClientTerrainsIdRouteImport.update({
  id: '/client/terrains/$id',
  path: '/client/terrains/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientMaisonsIdRoute = ClientMaisonsIdRouteImport.update({
  id: '/client/maisons/$id',
  path: '/client/maisons/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/carte': typeof CarteRoute
  '/documents': typeof DocumentsRoute
  '/maisons': typeof MaisonsRoute
  '/messagerie': typeof MessagerieRoute
  '/parametres': typeof ParametresRoute
  '/rapports': typeof RapportsRoute
  '/terrains': typeof TerrainsRoute
  '/transactions': typeof TransactionsRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/client/carte': typeof ClientCarteRoute
  '/client/': typeof ClientIndexRoute
  '/client/maisons/$id': typeof ClientMaisonsIdRoute
  '/client/terrains/$id': typeof ClientTerrainsIdRoute
  '/client/maisons/': typeof ClientMaisonsIndexRoute
  '/client/terrains/': typeof ClientTerrainsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/carte': typeof CarteRoute
  '/documents': typeof DocumentsRoute
  '/maisons': typeof MaisonsRoute
  '/messagerie': typeof MessagerieRoute
  '/parametres': typeof ParametresRoute
  '/rapports': typeof RapportsRoute
  '/terrains': typeof TerrainsRoute
  '/transactions': typeof TransactionsRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/client/carte': typeof ClientCarteRoute
  '/client': typeof ClientIndexRoute
  '/client/maisons/$id': typeof ClientMaisonsIdRoute
  '/client/terrains/$id': typeof ClientTerrainsIdRoute
  '/client/maisons': typeof ClientMaisonsIndexRoute
  '/client/terrains': typeof ClientTerrainsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/carte': typeof CarteRoute
  '/documents': typeof DocumentsRoute
  '/maisons': typeof MaisonsRoute
  '/messagerie': typeof MessagerieRoute
  '/parametres': typeof ParametresRoute
  '/rapports': typeof RapportsRoute
  '/terrains': typeof TerrainsRoute
  '/transactions': typeof TransactionsRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/client/carte': typeof ClientCarteRoute
  '/client/': typeof ClientIndexRoute
  '/client/maisons/$id': typeof ClientMaisonsIdRoute
  '/client/terrains/$id': typeof ClientTerrainsIdRoute
  '/client/maisons/': typeof ClientMaisonsIndexRoute
  '/client/terrains/': typeof ClientTerrainsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/carte'
    | '/documents'
    | '/maisons'
    | '/messagerie'
    | '/parametres'
    | '/rapports'
    | '/terrains'
    | '/transactions'
    | '/utilisateurs'
    | '/client/carte'
    | '/client/'
    | '/client/maisons/$id'
    | '/client/terrains/$id'
    | '/client/maisons/'
    | '/client/terrains/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/carte'
    | '/documents'
    | '/maisons'
    | '/messagerie'
    | '/parametres'
    | '/rapports'
    | '/terrains'
    | '/transactions'
    | '/utilisateurs'
    | '/client/carte'
    | '/client'
    | '/client/maisons/$id'
    | '/client/terrains/$id'
    | '/client/maisons'
    | '/client/terrains'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/carte'
    | '/documents'
    | '/maisons'
    | '/messagerie'
    | '/parametres'
    | '/rapports'
    | '/terrains'
    | '/transactions'
    | '/utilisateurs'
    | '/client/carte'
    | '/client/'
    | '/client/maisons/$id'
    | '/client/terrains/$id'
    | '/client/maisons/'
    | '/client/terrains/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  CarteRoute: typeof CarteRoute
  DocumentsRoute: typeof DocumentsRoute
  MaisonsRoute: typeof MaisonsRoute
  MessagerieRoute: typeof MessagerieRoute
  ParametresRoute: typeof ParametresRoute
  RapportsRoute: typeof RapportsRoute
  TerrainsRoute: typeof TerrainsRoute
  TransactionsRoute: typeof TransactionsRoute
  UtilisateursRoute: typeof UtilisateursRoute
  ClientCarteRoute: typeof ClientCarteRoute
  ClientIndexRoute: typeof ClientIndexRoute
  ClientMaisonsIdRoute: typeof ClientMaisonsIdRoute
  ClientTerrainsIdRoute: typeof ClientTerrainsIdRoute
  ClientMaisonsIndexRoute: typeof ClientMaisonsIndexRoute
  ClientTerrainsIndexRoute: typeof ClientTerrainsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/utilisateurs': {
      id: '/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof UtilisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terrains': {
      id: '/terrains'
      path: '/terrains'
      fullPath: '/terrains'
      preLoaderRoute: typeof TerrainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messagerie': {
      id: '/messagerie'
      path: '/messagerie'
      fullPath: '/messagerie'
      preLoaderRoute: typeof MessagerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maisons': {
      id: '/maisons'
      path: '/maisons'
      fullPath: '/maisons'
      preLoaderRoute: typeof MaisonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte': {
      id: '/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof CarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/client'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/carte': {
      id: '/client/carte'
      path: '/client/carte'
      fullPath: '/client/carte'
      preLoaderRoute: typeof ClientCarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/terrains/': {
      id: '/client/terrains/'
      path: '/client/terrains'
      fullPath: '/client/terrains/'
      preLoaderRoute: typeof ClientTerrainsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/maisons/': {
      id: '/client/maisons/'
      path: '/client/maisons'
      fullPath: '/client/maisons/'
      preLoaderRoute: typeof ClientMaisonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/terrains/$id': {
      id: '/client/terrains/$id'
      path: '/client/terrains/$id'
      fullPath: '/client/terrains/$id'
      preLoaderRoute: typeof ClientTerrainsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/maisons/$id': {
      id: '/client/maisons/$id'
      path: '/client/maisons/$id'
      fullPath: '/client/maisons/$id'
      preLoaderRoute: typeof ClientMaisonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  CarteRoute: CarteRoute,
  DocumentsRoute: DocumentsRoute,
  MaisonsRoute: MaisonsRoute,
  MessagerieRoute: MessagerieRoute,
  ParametresRoute: ParametresRoute,
  RapportsRoute: RapportsRoute,
  TerrainsRoute: TerrainsRoute,
  TransactionsRoute: TransactionsRoute,
  UtilisateursRoute: UtilisateursRoute,
  ClientCarteRoute: ClientCarteRoute,
  ClientIndexRoute: ClientIndexRoute,
  ClientMaisonsIdRoute: ClientMaisonsIdRoute,
  ClientTerrainsIdRoute: ClientTerrainsIdRoute,
  ClientMaisonsIndexRoute: ClientMaisonsIndexRoute,
  ClientTerrainsIndexRoute: ClientTerrainsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
